site_name: paks3c
site_url: https://paks3c.fr/ # URL finale de votre site
site_description: "Notes personnelles et cheatsheets sur la cybersécurité et l'IT." # Adaptez selon votre contenu
site_author: "Alexandre Lavefve" # Votre nom
theme:
  name: material
  language: fr
  scheme: slate
  features:
    - navigation.tabs
    - navigation.footer
    - content.code.copy
    - navigation.sections
    - navigation.top
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - markdown.extensions.nl2br
  - pymdownx.tabbed: # Permet de créer des onglets de contenu
      alternate_style: true

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/alexandre-lavefve/
  generator: false
  
plugins:
  - search # Ajouté
  - mkdocs-git-revision-date-localized-plugin
